### ISSUE TITLE
Bug in returned graph id

### ISSUE THREAD

**Issue by piscoroma** [netgroup-polito/frog4-orchestrator#10]
When the graph is deployed, the returned id is not always correct.
If the id starts with '0',  the first zero is truncated. 
For example: the graph id is: 09234, the put of the graph returns 9234.
The bug doesn't appear into the get of all graphs, but only in the put of a graph.

**Comment by frisso** [comment]
In fact, we should avoid "ids" and move to "uuid", which are becoming the stardard now:
https://en.wikipedia.org/wiki/Universally_unique_identifier

**Comment by farmanullahcs** [comment]
closed with [e0c829](https://github.com/netgroup-polito/frog4-orchestrator/commit/e0c829d00ccbec68a6e8f53344dc0eadf1d5f4cc)

**Comment by farmanullahcs** [comment]
The returned graph id example, when the graph is deployed. 
Is it correct ?

> {
  "nffg-uuid": "234204629483067032512745790389581325528"
}

**Comment by frisso** [comment]
Can we return the uuid as a string, with the proper formatting rules, which makes much easier to read?

**Comment by farmanullahcs** [comment]
Which one is more suitable? or to improve proper formatting

> {
"nffg-uuid": "6a188b06-3786-4c38-9a2c-4a75c1910975"
}


>{
"nffg-uuid": "3014c6f1039c4aea9cc17a046b20f197"
}

**Comment by frisso** [comment]
Personally, I've always seen the former. And I like it better too.
