### ISSUE TITLE
southbound API

### ISSUE THREAD

**Issue by ivanocerrato** [netgroup-polito/frog4-orchestrator#11]
The southbound API of the FROG orchestrator towards the domain orchestrators should be changed.
It must be the same already implemented between the GUI and the FROG orchestrator.

**Comment by gabrielecastellano** [comment]
Think this issue can be closed now? Cannot it?

**Comment by ivanocerrato** [comment]
I don't know. @farmanullahcs  is this issue solved? If yes, is it in a specific branch?

**Comment by farmanullahcs** [comment]
Southbound API is not yet implemented, currently we have Put API like {Domain_Orchestrator_Address/NF-FG/graph-id}.

The new put api should be:
1) Put api for insertion {Domain_Orchestrator_Address/NF-FG/}
2) Put api for updating {Domain_Orchestrator_Address/NF-FG/graph-id}

Moreover, the graph id will be assigned by the Domain-Orchestrator and the graph id will be deleted from the graph json.

**Comment by frisso** [comment]
I'm confused. Shouldn't we use "put" for creation, and "post" for update?

**Comment by ivanocerrato** [comment]
Note that the comment from @frisso is valid for each orchestrator.

**Comment by farmanullahcs** [comment]
As far as I know,

1) "POST" api for creation {Domain_Orchestrator_Address/NF-FG/}
2) "PUT" api for update {Domain_Orchestrator_Address/NF-FG/graph-id}

Is it correct ?

**Comment by frisso** [comment]
Yes, Farman, I wrote the wrong way. POST for creation, PUT for update.
Thanks for pointing this out.

**Comment by farmanullahcs** [comment]
Fixed in the branch [frog4-deployment](https://github.com/netgroup-polito/frog4-orchestrator/tree/frog4-deployment)
