### ISSUE TITLE
northbound API

### ISSUE THREAD

**Issue by ivanocerrato** [netgroup-polito/frog4-orchestrator#15]
Distinguish between new graph and update, using the PUT and POST methods. Currently, we use the PUT for both the operations.

**Comment by farmanullahcs** [comment]
closed with [b398123](https://github.com/netgroup-polito/frog4-orchestrator/commit/b39812333390bf43b7aebda89f1ae9fdcd004082)

**Comment by ivanocerrato** [comment]
@farmanullahcs please, note that this changes affect the GUI as well, which should use the proper API to talk with the orchestrator.
