### ISSUE TITLE
AttributeError: 'DomainInfo' object has no attribute 'getInterface'

### ISSUE THREAD

**Issue by rbrtbnfgl** [netgroup-polito/frog4-orchestrator#5]
On https://github.com/netgroup-polito/frog4-orchestrator/blob/domain-capabilities/orchestrator_core/scheduler.py
Multiple calls of the function getInterface:
https://github.com/netgroup-polito/frog4-orchestrator/blob/domain-capabilities/orchestrator_core/scheduler.py#L201
https://github.com/netgroup-polito/frog4-orchestrator/blob/domain-capabilities/orchestrator_core/scheduler.py#L231
https://github.com/netgroup-polito/frog4-orchestrator/blob/domain-capabilities/orchestrator_core/scheduler.py#L398
https://github.com/netgroup-polito/frog4-orchestrator/blob/domain-capabilities/orchestrator_core/scheduler.py#L412

The function was removed from https://github.com/netgroup-polito/frog4-orchestrator/blob/domain-capabilities/orchestrator_core/domain_info.py
on the following commit https://github.com/netgroup-polito/frog4-orchestrator/commit/d8c285532b97970d6c17a522a65bda340db1342d
done by @pamaglio91 

If a class specification is modified usually it should be checked on all the code that the removed methods are not used anymore.

**Comment by gabrielecastellano** [comment]
Scheduling logic has been restructured by commit baed05f0b429304f6b3fd77eb53b084baa1fa417, that also fixed this issue.
