### ISSUE TITLE
VNF templates

### ISSUE THREAD

**Issue by ivanocerrato** [netgroup-polito/frog4-orchestrator#7]
The FROG4 orchestrator should not retrieve the VNF template from the datastore.
It should schedule according to the functional-capabilities. 
The template should only be used by the domain orchestrators.

**Comment by ivanocerrato** [comment]
So, now does the FROG orchestrator still use/need the datastore?
In my understanding, it only used the dastore for templates (the url is indicated here https://github.com/netgroup-polito/frog4-orchestrator/blob/master/config/default-config.ini#L42) .
If the datastore is not used anymore anywhere in the orchestrator, I would remove that part of the configuration file.

**Comment by ivanocerrato** [comment]
So, now does the FROG orchestrator still use/need the datastore?
In my understanding, it only used the dastore for templates (the url is indicated here https://github.com/netgroup-polito/frog4-orchestrator/blob/master/config/default-config.ini#L42) .
If the datastore is not used anymore anywhere in the orchestrator, I would remove that part of the configuration file.

**Comment by gabrielecastellano** [comment]
The orchestrator does not use the datastore anymore, so the code need to be cleaned also.

**Comment by ivanocerrato** [comment]
Then I open a new issue about this.
