### ISSUE TITLE
FROG4 - connection with the datastore

### ISSUE THREAD

**Issue by ivanocerrato** [netgroup-polito/frog4-orchestrator#8]
The FROG4 orchestrator does not use the datastore.
Then that information should be removed from the configuration file https://github.com/netgroup-polito/frog4-orchestrator/blob/master/config/default-config.ini#L42-L53, as well as the README should be updated https://github.com/netgroup-polito/frog4-orchestrator/blob/master/README_INSTALL.md#frog-orchestrator-configuration-file .

Note that also the main README of the FROG project must be updated as well https://github.com/netgroup-polito/frog4/blob/master/docs/README_INSTALL.md#frog4-orchestrator , last bullet.

**Comment by gabrielecastellano** [comment]
closed with b0f7885208d8a69ca793a96d99f2f0b284e42c70 and ff299c1e764a3651fb9f209d06e1b4fc2442507a .
For the update of the frog4 project readme i think it's better to create an issue on that repository, since here the problem has been fixed.

**Comment by ivanocerrato** [comment]
I have updated the documentation in the [README](https://github.com/netgroup-polito/frog4/blob/master/README_INSTALL.md#frog4-orchestrator) of the FROG4 project.
