### ISSUE TITLE
the frog  does not use the field "functional-capability" to schedule the NF on a domain

### ISSUE THREAD

**Issue by ivanocerrato** [netgroup-polito/frog4-orchestrator#9]
It instead uses the name.

Actually, also every domain orchestrator has this problem.

**Comment by rbrtbnfgl** [comment]
It also requires the field vnf-template on the VNF specification of the graph that it should not be mandatory if the funcional-capability field is given.

**Comment by ivanocerrato** [comment]
Imho, the FROG orchestrator should not use the VNF template. This problem is reported [here](https://github.com/netgroup-polito/frog4-orchestrator/issues/8).
